spring.application.name=bookingmakeup

server.port=8080

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=BookingMakeup;encrypt=true;trustServerCertificate=true;sendTimeAsDateTime=false

spring.datasource.username=sa
spring.datasource.password=123456
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.mvc.hiddenmethod.filter.enabled=true

spring.servlet.multipart.enabled=true

# Giới hạn dung lượng 1 file tối đa 5MB
spring.servlet.multipart.max-file-size=5MB
# Giới hạn tổng dung lượng request tối đa 10MB
spring.servlet.multipart.max-request-size=10MB

# Đường dẫn thư mục sẽ lưu ảnh upload (tạo thư mục uploads ở gốc dự án)
upload.dir=uploads